add Mac support

diff --git a/src/7zcd b/src/7zcd
--- a/src/7zcd
+++ b/src/7zcd
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # 7zcd
 #
@@ -45,9 +45,22 @@ if [ "${?}" != "0" ]; then
   echo "Required tool realpath not found."
   exit 1
 fi
+SHASUM=$(which sha1sum shasum | head -1 | grep sha)
+if [ "${?}" != "0" ]; then
+  echo "Required tool sha1sum or shasum not found."
+  exit 1
+fi
+TMPDIR="/dev/shm"
+if [[ ! -d "${TMPDIR}" ]]; then
+  if [[ "$(uname)" == "Darwin" ]]; then
+    TMPDIR="/Volumes/7zetools"
+  else
+    echo "Required directory ${TMPDIR} not found, exiting."
+    exit 1
+  fi
+fi
 
 # Globals ############################################################
-TMPDIR="/dev/shm"
 USERTMPDIR="${TMPDIR}/7z-`whoami`"
 USERTMPDATADIR=""
 USERPASSFILE="${USERTMPDIR}/password"
@@ -107,7 +120,7 @@ if [ ! -f "${ENCNAME}" ]; then
   exit 1
 fi
 ENCPATH="`realpath ${ENCNAME}`"
-ENCID="`echo ${ENCPATH} | sha1sum | cut -f1 -d' '`"
+ENCID="`echo ${ENCPATH} | ${SHASUM} | cut -f1 -d' '`"
 
 # Password checking ##################################################
 if [ -f "${USERPASSFILE}" ]; then
@@ -119,7 +132,7 @@ if [ "${KEY1}" == "" ]; then
 fi
 
 # Determine which temporary storage to use ###########################
-ENCSIZE="`ls -s --block-size=1024 ${ENCPATH} | cut -d' ' -f1`"
+ENCSIZE="`BLOCKSIZE=1024 ls -s ${ENCPATH} | cut -d' ' -f1`"
 TMPSPACE="`df -k ${TMPDIR} | awk '/[0-9]%/{print $(NF-2)}'`"
 if [ "${ENCSIZE}" -lt "${TMPSPACE}" ]; then
   echo "Using ${TMPDIR} for temporary storage"
diff --git a/src/7zdec b/src/7zdec
--- a/src/7zdec
+++ b/src/7zdec
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # 7zdec
 #
@@ -40,9 +40,17 @@ if [ "${?}" != "0" ]; then
   echo "Required tool 7z not found."
   exit 1
 fi
+TMPDIR="/dev/shm"
+if [[ ! -d "${TMPDIR}" ]]; then
+  if [[ "$(uname)" == "Darwin" ]]; then
+    TMPDIR="/Volumes/7zetools"
+  else
+    echo "Required directory ${TMPDIR} not found, exiting."
+    exit 1
+  fi
+fi
 
 # Globals ############################################################
-TMPDIR="/dev/shm"
 USERTMPDIR="${TMPDIR}/7z-`whoami`"
 USERPASSFILE="${USERTMPDIR}/password"
 
diff --git a/src/7zfind b/src/7zfind
--- a/src/7zfind
+++ b/src/7zfind
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # 7zfind
 #
@@ -40,9 +40,17 @@ if [ "${?}" != "0" ]; then
   echo "Required tool 7z not found."
   exit 1
 fi
+TMPDIR="/dev/shm"
+if [[ ! -d "${TMPDIR}" ]]; then
+  if [[ "$(uname)" == "Darwin" ]]; then
+    TMPDIR="/Volumes/7zetools"
+  else
+    echo "Required directory ${TMPDIR} not found, exiting."
+    exit 1
+  fi
+fi
 
 # Globals ############################################################
-TMPDIR="/dev/shm"
 USERTMPDIR="${TMPDIR}/7z-`whoami`"
 USERPASSFILE="${USERTMPDIR}/password"
 
@@ -109,7 +117,7 @@ if [ "${KEY1}" == "" ]; then
 fi
 
 # Search specified file ##############################################
-find ${ARCHPATH} -name *.7z | \
+find ${ARCHPATH} -name "*.7z" | \
 while read ARCH; do
   7z l -p${KEY1} ${ARCH} | grep " $(basename -s .7z ${ARCH})/" | cut -c54- | grep -i ${SEARCHSTR}
 done
@@ -121,7 +129,7 @@ if [[ "${3}" != "" ]] && [[ -d "${3}" ]]; then
   read -p "Proceed to extract above files to ${DSTDIR} (y/n)? "
   echo ""
   if [ "$REPLY" = "y"  ] ; then
-    find ${ARCHPATH} -name *.7z | \
+    find ${ARCHPATH} -name "*.7z" | \
     while read ARCH; do
       7z l -p${KEY1} ${ARCH} | grep " $(basename -s .7z ${ARCH})/" | cut -c54- | grep -i ${SEARCHSTR} | \
       while read FILE; do
diff --git a/src/7zopen b/src/7zopen
--- a/src/7zopen
+++ b/src/7zopen
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # 7zopen
 #
@@ -45,9 +45,26 @@ if [ "${?}" != "0" ]; then
   echo "Required tool realpath not found."
   exit 1
 fi
+SHASUM=$(which sha1sum shasum | head -1 | grep sha)
+if [ "${?}" != "0" ]; then
+  echo "Required tool sha1sum or shasum not found."
+  exit 1
+fi
+if [ "${BASH_VERSINFO}" -lt 4 ]; then
+  echo "Required bash version (>=4) not found."
+  exit 1
+fi
+TMPDIR="/dev/shm"
+if [[ ! -d "${TMPDIR}" ]]; then
+  if [[ "$(uname)" == "Darwin" ]]; then
+    TMPDIR="/Volumes/7zetools"
+  else
+    echo "Required directory ${TMPDIR} not found, exiting."
+    exit 1
+  fi
+fi
 
 # Globals ############################################################
-TMPDIR="/dev/shm"
 USERTMPDIR="${TMPDIR}/7z-`whoami`"
 USERTMPDATADIR=""
 USERPASSFILE="${USERTMPDIR}/password"
@@ -150,7 +167,7 @@ if [ "${DEFPROG}" != "" ]; then
   fi
 fi
 ENCPATH="`realpath ${ENCNAME}`"
-ENCID="`echo ${ENCPATH} | sha1sum | cut -f1 -d' '`"
+ENCID="`echo ${ENCPATH} | ${SHASUM} | cut -f1 -d' '`"
 
 # Password checking ##################################################
 if [ -f "${USERPASSFILE}" ]; then
@@ -162,7 +179,7 @@ if [ "${KEY1}" == "" ]; then
 fi
 
 # Determine which temporary storage to use ###########################
-ENCSIZE="`ls -s --block-size=1024 ${ENCPATH} | cut -d' ' -f1`"
+ENCSIZE="`BLOCKSIZE=1024 ls -s ${ENCPATH} | cut -d' ' -f1`"
 TMPSPACE="`df -k ${TMPDIR} | awk '/[0-9]%/{print $(NF-2)}'`"
 if [ "${ENCSIZE}" -lt "${TMPSPACE}" ]; then
   echo "Using ${TMPDIR} for temporary storage"
@@ -202,16 +219,22 @@ fi
 FIRSTFILE="`find . -type f | head -1`"
 MIME="`file --mime-type -b ${FIRSTFILE}`"
 CUSTPROG="`echo $MIME | sed 's/\///g' | awk '{print toupper($0)}'`PROG"
+PROGARG=""
 echo "Mime-type:  ${MIME}"
 
 if [ "${DEFPROG}" == "" ]; then
   # If not manually specified at cmd line, check if custom program set
   DEFPROG=${PROG[${CUSTPROG}]}
 
+  # If no custom program set, use system default
   if [ "${DEFPROG}" == "" ]; then
-    # If no custom program set, use system default
-    DEFAPP="`xdg-mime query default ${MIME}`"
-    DEFPROG="`echo ${DEFAPP} | cut -f1 -d.`"
+    if [[ "$(uname)" == "Darwin" ]]; then
+      DEFPROG="open"
+      PROGARG="-Wn"
+    else
+      DEFAPP="`xdg-mime query default ${MIME}`"
+      DEFPROG="`echo ${DEFAPP} | cut -f1 -d.`"
+    fi
   fi
 fi
 which ${DEFPROG} > /dev/null
@@ -225,14 +248,14 @@ fi
 
 # Calculate checksum before open #####################################
 ALLFILES=($(find . -type f | cut -c3-1024))
-ORGCHKSUM=`cat ${ALLFILES[@]} | sha1sum -b | cut -f1 -d' '`
+ORGCHKSUM=`cat ${ALLFILES[@]} | ${SHASUM} -b | cut -f1 -d' '`
 
 # Open decrypted files ###############################################
-${DEFPROG} ${ALLFILES[@]}
+${DEFPROG} ${PROGARG} ${ALLFILES[@]}
 
 # Recompress opened files if modified ################################
 echo ""
-NEWCHKSUM=`cat ${ALLFILES[@]} | sha1sum -b | cut -f1 -d' '`
+NEWCHKSUM=`cat ${ALLFILES[@]} | ${SHASUM} -b | cut -f1 -d' '`
 if [ "${ORGCHKSUM}" != "${NEWCHKSUM}" ]; then
   echo "Updating ${ENCPATH}, do not stop this program"
   7z u -mhe=on -mx0 -p${KEY1} ${ENCPATH} ${ALLFILES[@]}
diff --git a/src/7zpass b/src/7zpass
--- a/src/7zpass
+++ b/src/7zpass
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
 # 7zpass
 #
@@ -40,9 +40,17 @@ if [ "${?}" != "0" ]; then
   echo "Required tool 7z not found."
   exit 1
 fi
+TMPDIR="/dev/shm"
+if [[ ! -d "${TMPDIR}" ]]; then
+  if [[ "$(uname)" == "Darwin" ]]; then
+    TMPDIR="/Volumes/7zetools"
+  else
+    echo "Required directory ${TMPDIR} not found, exiting."
+    exit 1
+  fi
+fi
 
 # Globals ############################################################
-TMPDIR="/dev/shm"
 USERTMPDIR="${TMPDIR}/7z-`whoami`"
 USERPASSFILE="${USERTMPDIR}/password"
 
@@ -98,15 +106,6 @@ elif [ "${1}" == "--unsafe" ] ; then
   KEY2="${2}"
 fi
 
-# Prepare temporary storage ##########################################
-mkdir -p ${USERTMPDIR}
-if [ "${?}" != "0" ]; then
-  echo "Cannot create ${USERTMPDIR}"
-  exit 1
-else
-  chmod go-rwx ${USERTMPDIR}
-fi
-
 # Retrieve user password and perform validation ######################
 if [ "${UNSAFE}" != "1" ]; then
   read -s -p "Enter password (will not be echoed) :" KEY1
@@ -121,12 +120,61 @@ if [ "${KEY1}" != "${KEY2}" ]; then
   exit 1
 fi
 
+# Ram disk creation when password is set #############################
+if [ "${KEY1}" != "" ]; then
+  if [[ "$(uname)" == "Darwin" ]] && [[ ! -d "${TMPDIR}" ]]; then
+    SIZEMB="2048"
+    SYSMB="$(( $(sysctl hw.memsize | cut -d':' -f2) / 1024 / 1024 ))"
+    MAXMB="$(( ${SYSMB} / 2 ))"
+    if [[ "${SIZEMB}" -gt "${MAXMB}" ]]; then
+      SIZEMB="${MAXMB}"
+    fi
+    SECTORS=$((2048 * ${SIZEMB}))
+    DISKID=$(hdiutil attach -nomount ram://${SECTORS})
+    if [ "${?}" == "0" ]; then
+      diskutil erasevolume HFS+ "$(basename ${TMPDIR})" ${DISKID} > /dev/null
+      if [ "${?}" != "0" ]; then
+        echo "error mounting ram disk, exiting."
+        hdiutil detach ${DISKID}
+        exit 1
+      fi
+    else
+      echo "error creating ram disk, exiting."
+      exit 1
+    fi
+  fi
+fi
+
+# Prepare temporary storage ##########################################
+mkdir -p ${USERTMPDIR}
+if [ "${?}" != "0" ]; then
+  echo "Cannot create ${USERTMPDIR}"
+  exit 1
+else
+  chmod go-rwx ${USERTMPDIR}
+fi
+
 # Store password in temporary file ###################################
 rm ${USERPASSFILE} 2> /dev/null
 if [ "${KEY1}" != "" ]; then
   touch ${USERPASSFILE}
   chmod go-rwx ${USERPASSFILE}
   echo ${KEY1} >> ${USERPASSFILE}
+fi
+
+# Ram disk cleanup when password is cleared ##########################
+if [ "${KEY1}" == "" ]; then
+  if [[ "$(uname)" == "Darwin" ]] && [[ -d "${TMPDIR}" ]] && [[ "$(dirname ${TMPDIR})" == "/Volumes" ]]; then
+    DISKID=$(mount | grep "${TMPDIR}" | cut -d' ' -f1)
+    if [ "${DISKID}" != "" ]; then
+      hdiutil detach ${DISKID} > /dev/null
+      if [ "${?}" != "0" ]; then
+        echo "warning: failed to unmount ${TMPDIR} and deleting ram disk ${DISKID}"
+      fi
+    else
+      echo "warning: failed to determine disk id for ${TMDIR}"
+    fi
+  fi
 fi
 
 # Feedback result to user ############################################
